#!/usr/bin/env python3
"""
Integration Tests — Calcure Calendar & Task Manager
====================================================
Integration tests verify that multiple modules work TOGETHER correctly.
Each test exercises a realistic pipeline: load → transform → filter → save.

Unlike unit tests (single class in isolation), these tests cross module
boundaries and validate end-to-end data flow.
"""

import sys
import os
import time
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

from calcure.data import (
    Task, UserEvent, Event, Timer, Tasks, Events, Birthdays,
    Status, Frequency, RepeatedEvents
)
from calcure.calendars import Calendar


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_timer(stamps=None):
    return Timer(stamps or [])


def make_task(item_id=0, name="Task", status=Status.NORMAL,
              privacy=False, year=0, month=0, day=0):
    return Task(item_id, name, status, make_timer(), privacy, year, month, day)


def make_event(item_id=0, year=2024, month=3, day=1, name="Event",
               repetition=1, frequency=Frequency.ONCE,
               status=Status.NORMAL, privacy=False):
    return UserEvent(item_id, year, month, day, name, repetition,
                     frequency, status, privacy)


def make_config(tasks_file, events_file):
    class FakeCF:
        TASKS_FILE = tasks_file
        EVENTS_FILE = events_file
        USE_PERSIAN_CALENDAR = False
    return FakeCF()


def make_ics_config(task_files=None, event_files=None):
    class FakeCF:
        ICS_TASK_FILES = task_files
        ICS_EVENT_FILES = event_files
        USE_PERSIAN_CALENDAR = False
    return FakeCF()


class MockScreen:
    def __init__(self, year, month, day):
        self.year = year
        self.month = month
        self.day = day


# ===========================================================================
# 1. EVENTS + REPEATED EVENTS + FILTER PIPELINE
# ===========================================================================

class TestEventsRepeatedEventsFilterPipeline(unittest.TestCase):
    """
    Integration: data.Events → data.RepeatedEvents → Collection.filter_events_that_day.
    Validates that recurring events generated by RepeatedEvents are properly
    discoverable through the filter API.
    """

    def test_weekly_event_visible_on_repeated_date(self):
        """
        Create a weekly event starting 2024-03-01. RepeatedEvents generates
        occurrences on March 8 and 15. Filtering March 8 must return that event.
        """
        user_events = Events()
        user_events.add_item(make_event(
            item_id=0, year=2024, month=3, day=1,
            name="Weekly standup", repetition=3, frequency=Frequency.WEEKLY
        ))
        repeated = RepeatedEvents(user_events, False, 2024)

        screen = MockScreen(2024, 3, 8)
        result = repeated.filter_events_that_day(screen)
        self.assertEqual(len(result.items), 1)
        self.assertEqual(result.items[0].name, "Weekly standup")

    def test_original_event_not_in_repeated_collection(self):
        """
        The original event (March 1) must NOT appear in the RepeatedEvents
        collection — it remains only in user_events.
        """
        user_events = Events()
        user_events.add_item(make_event(
            item_id=0, year=2024, month=3, day=1,
            name="Original", repetition=3, frequency=Frequency.WEEKLY
        ))
        repeated = RepeatedEvents(user_events, False, 2024)

        screen = MockScreen(2024, 3, 1)
        result = repeated.filter_events_that_day(screen)
        self.assertEqual(len(result.items), 0)

    def test_original_event_visible_in_user_events(self):
        """
        Conversely, the original date IS visible when querying user_events directly.
        """
        user_events = Events()
        user_events.add_item(make_event(
            item_id=0, year=2024, month=3, day=1,
            name="Original", repetition=3, frequency=Frequency.WEEKLY
        ))
        screen = MockScreen(2024, 3, 1)
        result = user_events.filter_events_that_day(screen)
        self.assertEqual(len(result.items), 1)

    def test_monthly_event_filter_across_months(self):
        """
        A monthly event on 2024-01-15 with repetition=3 produces occurrences
        on Feb 15 and Mar 15. All three months can be queried independently.
        """
        user_events = Events()
        user_events.add_item(make_event(
            item_id=0, year=2024, month=1, day=15,
            name="Monthly review", repetition=3, frequency=Frequency.MONTHLY
        ))
        repeated = RepeatedEvents(user_events, False, 2024)

        for month, expected_count in [(1, 0), (2, 1), (3, 1)]:
            screen = MockScreen(2024, month, 15)
            result = repeated.filter_events_that_day(screen)
            self.assertEqual(len(result.items), expected_count,
                             f"Wrong count for month {month}")

    def test_combined_original_and_repeated_total(self):
        """
        On a day that has both an original event AND a repeated event from a
        different original, the combined queries return the right totals.
        """
        user_events = Events()
        user_events.add_item(make_event(
            item_id=0, year=2024, month=4, day=10,
            name="Original on 10th", repetition=1, frequency=Frequency.ONCE
        ))
        user_events.add_item(make_event(
            item_id=1, year=2024, month=4, day=3,
            name="Weekly from 3rd", repetition=2, frequency=Frequency.WEEKLY
        ))
        repeated = RepeatedEvents(user_events, False, 2024)

        screen = MockScreen(2024, 4, 10)
        from_original = user_events.filter_events_that_day(screen)
        from_repeated = repeated.filter_events_that_day(screen)
        total = len(from_original.items) + len(from_repeated.items)
        self.assertEqual(total, 2)


# ===========================================================================
# 2. TASKS SAVE → LOAD → MODIFY → SAVE CYCLE
# ===========================================================================

class TestTaskSaveLoadModifyCycle(unittest.TestCase):
    """
    Integration: data.Tasks → savers.TaskSaverCSV → loaders.TaskLoaderCSV → modify → save again.
    Validates that the full persistence cycle preserves state correctly.
    """

    def setUp(self):
        self.tmpfile = tempfile.NamedTemporaryFile(suffix=".csv", delete=False, mode="w")
        self.tmpfile.close()
        self.filepath = self.tmpfile.name
        self.cf = make_config(self.filepath, self.filepath)

    def tearDown(self):
        for path in [self.filepath, self.filepath + ".bak"]:
            if os.path.exists(path):
                os.unlink(path)

    def test_save_then_load_preserves_all_fields(self):
        """
        Save 3 tasks (with different statuses and privacy) then reload.
        All field values must be identical.
        """
        from calcure.savers import TaskSaverCSV
        from calcure.loaders import TaskLoaderCSV

        tasks = Tasks()
        tasks.add_item(Task(0, "Normal public",    Status.NORMAL,      make_timer(), False, 0, 0, 0))
        tasks.add_item(Task(1, "Done private",     Status.DONE,        make_timer(), True,  2025, 3, 15))
        tasks.add_item(Task(2, "Important public", Status.IMPORTANT,   make_timer(), False, 0, 0, 0))
        TaskSaverCSV(tasks, self.cf).save()

        loaded = TaskLoaderCSV(self.cf).load()
        self.assertEqual(len(loaded.items), 3)

        names = {t.name: t for t in loaded.items}
        self.assertEqual(names["Normal public"].status,    Status.NORMAL)
        self.assertEqual(names["Done private"].status,     Status.DONE)
        self.assertEqual(names["Done private"].privacy,    True)
        self.assertEqual(names["Done private"].year,       2025)
        self.assertEqual(names["Important public"].status, Status.IMPORTANT)

    def test_modify_after_load_and_resave(self):
        """
        Load tasks, modify a status, save again, reload.
        The modification must survive the second save/load cycle.
        """
        from calcure.savers import TaskSaverCSV
        from calcure.loaders import TaskLoaderCSV

        tasks = Tasks()
        tasks.add_item(Task(0, "Task to modify", Status.NORMAL, make_timer(), False, 0, 0, 0))
        TaskSaverCSV(tasks, self.cf).save()

        loaded = TaskLoaderCSV(self.cf).load()
        loaded.toggle_item_status(0, Status.DONE)
        TaskSaverCSV(loaded, self.cf).save()

        reloaded = TaskLoaderCSV(self.cf).load()
        self.assertEqual(reloaded.items[0].status, Status.DONE)

    def test_delete_and_resave(self):
        """
        Add 3 tasks, save, load, delete one, save again, reload.
        Only 2 tasks should remain.
        """
        from calcure.savers import TaskSaverCSV
        from calcure.loaders import TaskLoaderCSV

        tasks = Tasks()
        for i, name in enumerate(["Alpha", "Beta", "Gamma"]):
            tasks.add_item(Task(i, name, Status.NORMAL, make_timer(), False, 0, 0, 0))
        TaskSaverCSV(tasks, self.cf).save()

        loaded = TaskLoaderCSV(self.cf).load()
        loaded.delete_item(1)
        TaskSaverCSV(loaded, self.cf).save()

        reloaded = TaskLoaderCSV(self.cf).load()
        self.assertEqual(len(reloaded.items), 2)
        names = {t.name for t in reloaded.items}
        self.assertNotIn("Beta", names)

    def test_changed_flag_reset_after_save(self):
        """
        After TaskSaverCSV.save(), the changed flag on the Tasks collection
        is reset to False.
        """
        from calcure.savers import TaskSaverCSV

        tasks = Tasks()
        tasks.add_item(make_task())
        self.assertTrue(tasks.changed)
        TaskSaverCSV(tasks, self.cf).save()
        self.assertFalse(tasks.changed)


# ===========================================================================
# 3. EVENTS SAVE → LOAD → REPEATED EVENTS PIPELINE
# ===========================================================================

class TestEventsSaveLoadRepeatedPipeline(unittest.TestCase):
    """
    Integration: Events → EventSaverCSV → EventLoaderCSV → RepeatedEvents → filter.
    Validates that a recurring event stored and reloaded from CSV still produces
    the correct repeated occurrences.
    """

    def setUp(self):
        self.tmpfile = tempfile.NamedTemporaryFile(suffix=".csv", delete=False, mode="w")
        self.tmpfile.close()
        self.filepath = self.tmpfile.name
        self.cf = make_config(self.filepath, self.filepath)

    def tearDown(self):
        for path in [self.filepath, self.filepath + ".bak"]:
            if os.path.exists(path):
                os.unlink(path)

    def test_weekly_event_round_trip_still_recurs(self):
        """
        Save a weekly event (repetition=4), reload it, build RepeatedEvents.
        Must produce 3 repeated occurrences (same as before save).
        """
        from calcure.savers import EventSaverCSV
        from calcure.loaders import EventLoaderCSV

        events = Events()
        events.add_item(UserEvent(0, 2024, 1, 1, "Weekly",
                                  4, Frequency.WEEKLY, Status.NORMAL, False))
        EventSaverCSV(events, self.cf).save()

        loaded = EventLoaderCSV(self.cf).load()
        repeated = RepeatedEvents(loaded, False, 2024)
        self.assertEqual(len(repeated.items), 3)

    def test_event_frequency_preserved_through_csv(self):
        """
        MONTHLY frequency survives a save/load cycle and still generates
        the correct number of monthly repetitions.
        """
        from calcure.savers import EventSaverCSV
        from calcure.loaders import EventLoaderCSV

        events = Events()
        events.add_item(UserEvent(0, 2024, 1, 15, "Monthly report",
                                  3, Frequency.MONTHLY, Status.NORMAL, False))
        EventSaverCSV(events, self.cf).save()

        loaded = EventLoaderCSV(self.cf).load()
        repeated = RepeatedEvents(loaded, False, 2024)
        self.assertEqual(len(repeated.items), 2)

    def test_event_status_preserved_in_repeated_events(self):
        """
        An IMPORTANT event saved and reloaded must produce IMPORTANT repeated events.
        """
        from calcure.savers import EventSaverCSV
        from calcure.loaders import EventLoaderCSV

        events = Events()
        events.add_item(UserEvent(0, 2024, 3, 1, "Critical",
                                  3, Frequency.WEEKLY, Status.IMPORTANT, False))
        EventSaverCSV(events, self.cf).save()

        loaded = EventLoaderCSV(self.cf).load()
        repeated = RepeatedEvents(loaded, False, 2024)
        for r in repeated.items:
            self.assertEqual(r.status, Status.IMPORTANT)


# ===========================================================================
# 4. TASKS + TIMER INTEGRATION
# ===========================================================================

class TestTasksTimerIntegration(unittest.TestCase):
    """
    Integration: Tasks collection + Timer lifecycle.
    Validates that timer state changes propagate correctly through the Tasks API.
    """

    def test_start_pause_resume_reset_cycle(self):
        """
        Full timer lifecycle on a single task:
        add → start → pause → resume → reset → verify clean state.
        """
        tasks = Tasks()
        tasks.add_item(make_task(item_id=0))

        # Start
        tasks.add_timestamp_for_task(0)
        self.assertTrue(tasks.has_active_timer)
        self.assertTrue(tasks.items[0].timer.is_counting)

        # Pause
        tasks.add_timestamp_for_task(0)
        self.assertFalse(tasks.items[0].timer.is_counting)
        self.assertFalse(tasks.has_active_timer)

        # Resume
        tasks.add_timestamp_for_task(0)
        self.assertTrue(tasks.items[0].timer.is_counting)

        # Reset
        tasks.reset_timer_for_task(0)
        self.assertFalse(tasks.items[0].timer.is_started)
        self.assertFalse(tasks.has_active_timer)

    def test_only_one_timer_active_after_pause_others(self):
        """
        Start 3 task timers, then call pause_all_other_timers(1).
        Only task 1 should remain running; tasks 0 and 2 are paused.
        """
        tasks = Tasks()
        for i in range(3):
            tasks.add_item(make_task(item_id=i))
            tasks.add_timestamp_for_task(i)

        tasks.pause_all_other_timers(1)

        self.assertFalse(tasks.items[0].timer.is_counting)
        self.assertTrue(tasks.items[1].timer.is_counting)
        self.assertFalse(tasks.items[2].timer.is_counting)
        self.assertTrue(tasks.has_active_timer)

    def test_timer_elapsed_time_persists_across_collection_rename(self):
        """
        Renaming a task via the collection API does not affect its timer state.
        """
        tasks = Tasks()
        tasks.add_item(make_task(item_id=0, name="Old name"))
        tasks.add_timestamp_for_task(0)
        tasks.rename_item(0, "New name")

        self.assertEqual(tasks.items[0].name, "New name")
        self.assertTrue(tasks.items[0].timer.is_counting)


# ===========================================================================
# 5. CALENDAR + WEEK NUMBERS + FILTER INTEGRATION
# ===========================================================================

class TestCalendarFilterIntegration(unittest.TestCase):
    """
    Integration: Calendar (calendars.py) + Collection.filter_events_that_month.
    Validates that calendar grid dimensions align with event filtering results.
    """

    def test_week_count_matches_grid_rows(self):
        """
        For every month of 2024, the number of week numbers returned by
        month_week_numbers() equals the number of grid rows from monthdayscalendar().
        """
        cal = Calendar(0, False)
        for month in range(1, 13):
            rows = cal.monthdayscalendar(2024, month)
            wnums = cal.month_week_numbers(2024, month)
            self.assertEqual(len(rows), len(wnums),
                             f"Mismatch for month {month}")

    def test_filter_returns_subset_of_full_month_grid(self):
        """
        Events filtered for a specific day must be a strict subset of all
        events that appear in that month's filter.
        """
        events = Events()
        for day in [1, 5, 10, 15, 20, 25]:
            events.add_item(make_event(item_id=day, year=2024, month=5, day=day,
                                       name=f"Day {day} event"))

        month_screen = MockScreen(2024, 5, 1)
        day_screen = MockScreen(2024, 5, 10)

        month_result = events.filter_events_that_month(month_screen)
        day_result = events.filter_events_that_day(day_screen)

        self.assertEqual(len(month_result.items), 6)
        self.assertEqual(len(day_result.items), 1)
        self.assertIn(day_result.items[0].name,
                      {e.name for e in month_result.items})

    def test_all_31_days_of_march_are_reachable_via_calendar(self):
        """
        monthdayscalendar for March 2024 must contain all 31 days,
        all of which can be used as filter screen.day values.
        """
        cal = Calendar(0, False)
        events = Events()
        for day in range(1, 32):
            events.add_item(make_event(item_id=day, year=2024, month=3, day=day,
                                       name=f"Event {day}"))

        all_days_in_grid = {
            day
            for week in cal.monthdayscalendar(2024, 3)
            for day in week
            if day != 0
        }
        self.assertEqual(len(all_days_in_grid), 31)

        for day in all_days_in_grid:
            screen = MockScreen(2024, 3, day)
            result = events.filter_events_that_day(screen)
            self.assertEqual(len(result.items), 1)


# ===========================================================================
# 6. ICS IMPORT + DOMAIN PIPELINES
# ===========================================================================

class TestICSImportPipelines(unittest.TestCase):
    """
    Integration: LoaderICS subclasses + domain objects.
    These tests execute real .ics files through the import pipeline and then
    validate the resulting Tasks/Events collections.
    """

    def test_vtodo_file_import_keeps_completed_task_and_skips_cancelled(self):
        """
        TaskLoaderICS should import a COMPLETED VTODO as DONE, preserve its due
        date, and ignore a CANCELLED VTODO from the same calendar file.
        """
        from calcure.loaders import TaskLoaderICS

        ics_text = """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Calcure Test//EN
BEGIN:VTODO
SUMMARY:Done item
STATUS:COMPLETED
PRIORITY:1
DUE;VALUE=DATE:20240415
END:VTODO
BEGIN:VTODO
SUMMARY:Cancelled item
STATUS:CANCELLED
DUE;VALUE=DATE:20240416
END:VTODO
END:VCALENDAR
"""

        with tempfile.NamedTemporaryFile(suffix=".ics", delete=False, mode="w",
                                         encoding="utf-8") as f:
            f.write(ics_text)
            filepath = f.name

        try:
            loaded = TaskLoaderICS(make_ics_config(task_files=[filepath])).load()
            self.assertEqual(len(loaded.items), 1)
            task = loaded.items[0]
            self.assertEqual(task.name, "Done item")
            self.assertEqual(task.status, Status.DONE)
            self.assertEqual((task.year, task.month, task.day), (2024, 4, 15))
        finally:
            os.unlink(filepath)

    def test_all_day_multiday_ics_event_loads_as_daily_repetition(self):
        """
        EventLoaderICS should turn an all-day multi-day VEVENT into a DAILY
        event with repetition equal to the number of included calendar days.
        """
        from calcure.loaders import EventLoaderICS

        ics_text = """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Calcure Test//EN
BEGIN:VEVENT
SUMMARY:Festival
DTSTART;VALUE=DATE:20240301
DTEND;VALUE=DATE:20240304
END:VEVENT
END:VCALENDAR
"""

        with tempfile.NamedTemporaryFile(suffix=".ics", delete=False, mode="w",
                                         encoding="utf-8") as f:
            f.write(ics_text)
            filepath = f.name

        try:
            loaded = EventLoaderICS(make_ics_config(event_files=[filepath])).load()
            self.assertEqual(len(loaded.items), 1)
            event = loaded.items[0]
            self.assertEqual(event.frequency, Frequency.DAILY)
            self.assertEqual(event.repetition, 3)
        finally:
            os.unlink(filepath)

    def test_rrule_event_with_exdate_filters_only_remaining_occurrence(self):
        """
        An RRULE event imported from .ics should flow through EventLoaderICS into
        RepeatedEvents, and EXDATE must suppress the excluded repeated date.
        """
        from calcure.loaders import EventLoaderICS

        ics_text = """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Calcure Test//EN
BEGIN:VEVENT
SUMMARY:Recurring
DTSTART;VALUE=DATE:20240301
DTEND;VALUE=DATE:20240302
RRULE:FREQ=WEEKLY;COUNT=3
EXDATE;VALUE=DATE:20240308
END:VEVENT
END:VCALENDAR
"""

        with tempfile.NamedTemporaryFile(suffix=".ics", delete=False, mode="w",
                                         encoding="utf-8") as f:
            f.write(ics_text)
            filepath = f.name

        try:
            loaded = EventLoaderICS(make_ics_config(event_files=[filepath])).load()
            repeated = RepeatedEvents(loaded, False, 2024)

            excluded = repeated.filter_events_that_day(MockScreen(2024, 3, 8))
            remaining = repeated.filter_events_that_day(MockScreen(2024, 3, 15))

            self.assertEqual(len(excluded.items), 0)
            self.assertEqual(len(remaining.items), 1)
            self.assertEqual(remaining.items[0].name, "Recurring")
        finally:
            os.unlink(filepath)


if __name__ == "__main__":
    unittest.main(verbosity=2)
